Mendaftarkan diri sebagai volunter
dicodingacademy/VolunterPembuatanAplikasi pull request #27
Opened 2021-07-25 08:58 UTC by alamisaja

belajar mengikuti kursus di Dicoding ternyata menyenangkan dan bikin deg degan

2021-07-27 03:33 UTC, dicodingreviewer requested changes

2021-07-27 03:33 UTC, dicodingreviewer commented on README.md
> +* Nur Alamsyah, [GitHub](https://github.com/alamisaja)
Hai kak, sepertinya terdapat kesalahan format. Kakak kurang titik di belakang tanda kurung tutup. Silakan perbaiki terlebih dahulu ya kak.

2021-07-27 03:34 UTC, dicodingreviewer commented
Hai kak @alamisaja

Terima kasih atas pendaftaran volunter yang dilakukan. Sayangnya, kakak masih belum menggunakan format yang benar. Silakan perbaiki. Sekalin, lakukan resolve conflict pada PR kakak. Kami tunggu ya kak. 

Terima kasih.

2021-08-25 02:16 UTC, merged

2021-08-25 02:16 UTC, gilangadhan commented
Hai kak,

Terima kasih atas pendaftaran yang dilakukan.
Kami ucapkan selamat atas diterimanya kakak menjadi salah satu volunter dalam pembuatan aplikasi Dicoding.
Selamat berkontribusi ya kak!

Regards
Dicoding Reviewer