Mendaftarkan Diri sebagai Volunter
dicodingacademy/VolunterPembuatanAplikasi pull request #28
Opened 2021-07-25 10:58 UTC by liemlui

Hai,
Saya Aloysius Alfa bersedia menjadi Volunter Pembuatan Aplikasi Dicoding

2021-07-27 03:36 UTC, dicodingreviewer requested changes

2021-07-27 03:36 UTC, dicodingreviewer commented on README.md
> +* Aloysius Alfa, [WebsitePribadi](https://www.kost48surabaya.com/lui/).
Hai kak, 

Untuk website pribadi, baiknya gunakan nama websitenya saja seperti kak Ferri Yusra atau kak Oon.
Kakak tidak perlu menuliskan "WebistePribadi" karena informasi terlalu general.

Terima kasih

2021-07-27 06:23 UTC, liemlui commented
Baik, sudah saya solve

2021-07-29 06:48 UTC, dicodingreviewer approved these changes

2021-07-29 06:48 UTC, dicodingreviewer commented on README.md
> +* Aloysius Alfa, [GitHub](https://www.github.com/liemlui/).
Mantap mas!

2021-07-29 06:49 UTC, dicodingreviewer commented
Hai kak @liemlui ,

Terima kasih atas pendaftaran yang dilakukan.
Kami ucapkan selamat atas diterimanya kakak menjadi salah satu volunter dalam pembuatan aplikasi Dicoding.
Selamat berkontribusi ya kak!

Regards
Dicoding Reviewer

2021-07-29 06:49 UTC, merged