Mendaftarkan diri sebagai Volunteer
dicodingacademy/VolunterPembuatanAplikasi pull request #29
Opened 2021-07-25 11:55 UTC by hendraditoda

Saya Hendradito Dwi A, bersedia menjadi volunteer Pembuatan Aplikasi Dicoding

2021-07-27 03:38 UTC, dicodingreviewer requested changes

2021-07-27 03:38 UTC, dicodingreviewer commented on README.md
> +* * Hendradito, [Linkedin](https://www.linkedin.com/in/hendraditodwia/).
Hai kak, sepertinya format yang dilakukan kurang tepat.

1. Cukup menuliskan satu bintang di depan kalimat (*).
2. Teks "Linkedin" Seharusnya "LinkedIn". 

Silakan perbaiki, jangan lupa untuk melakukan resolve conflict ya kak.

Terima kasih.

2021-07-27 04:50 UTC, hendraditoda commented on README.md
> +* * Hendradito, [Linkedin](https://www.linkedin.com/in/hendraditodwia/).
Baik kak Sudah saya perbaiki terimakasih banyak kak atas bantuan dan informasinya

2021-07-29 06:50 UTC, dicodingreviewer approved these changes

2021-07-29 06:50 UTC, dicodingreviewer commented on README.md
> +* Hendradito, [LinkedIn](https://www.linkedin.com/in/hendraditodwia/).
Mantap kak!

2021-07-29 06:51 UTC, merged

2021-07-29 06:51 UTC, dicodingreviewer commented
Hai kak,

Terima kasih atas pendaftaran yang dilakukan.
Kami ucapkan selamat atas diterimanya kakak menjadi salah satu volunter dalam pembuatan aplikasi Dicoding.
Selamat berkontribusi ya kak!

Regards
Dicoding Reviewer