Mendaftarkan diri sebagai Volunter
dicodingacademy/VolunterPembuatanAplikasi pull request #33
Opened 2021-07-26 03:19 UTC by sudarmintosenlau

Saya Sudarminto Senlau, bersedia menjadi Volunter analist data di Dicoding

2021-07-27 03:40 UTC, dicodingreviewer requested changes

2021-07-27 03:40 UTC, dicodingreviewer commented on README.md
> +* Sudarminto Senlau, [Linkedin](https://www.linkedin.com/in/sudarminto-senlau/)
Hai kak Sudarminto

Sepertinya format yang dimasukkan kakak masih kurang tepat.
1. Seharusnya ada titik di akhir kalimat.
2. Teks "Linkedin" seharusnya "LinkedIn".

Terima kasih

2021-07-27 17:48 UTC, sudarmintosenlau commented on README.md
> +* Sudarminto Senlau, [Linkedin](https://www.linkedin.com/in/sudarminto-senlau/)
Oke. Terimakasih kak

2021-07-27 17:50 UTC, sudarmintosenlau commented
Sudah diperbaiki kak

2021-07-29 06:55 UTC, dicodingreviewer approved these changes

2021-07-29 06:55 UTC, dicodingreviewer commented on README.md
> +
Lain kali, untuk baris terakhir jika tidak diperlukan silakan dihapus ya kak. Semangat!

2021-07-29 06:55 UTC, merged

2021-07-29 06:55 UTC, dicodingreviewer commented
Hai kak,

Terima kasih atas pendaftaran yang dilakukan.
Kami ucapkan selamat atas diterimanya kakak menjadi salah satu volunter dalam pembuatan aplikasi Dicoding.
Selamat berkontribusi ya kak!

Regards
Dicoding Reviewer