Mendaftarkan diri sebagai volunteer
dicodingacademy/VolunterPembuatanAplikasi pull request #34
Opened 2021-07-26 03:27 UTC by Ndann457216

Saya Hamdan bersedia menjadi Volunteer pembuatan aplikasi Dicoding.

2021-07-26 03:31 UTC, Ndann457216 commented
Hi Hamdan,
Instagram kamu gg yaa..

2021-07-27 03:43 UTC, dicodingreviewer requested changes

2021-07-27 03:43 UTC, dicodingreviewer commented on README.md
> +* Muhammad Hamdan, [Instagram](https://www.instagram.com/m._.hamdan/).
Hai kak, terima kasih banyak atas pendaftaran yang dilakukan. Setelah kami tinjau, instagram kakak masih belum layak untuk dijadikan portofolio. Silakan gunakan akun GitHub, LinkedIn, Website Pribadi, atau portofolio lainnya. 

Terima kasih banyak

2021-08-25 02:17 UTC, merged

2021-08-25 02:17 UTC, gilangadhan commented
Hai kak,

Terima kasih atas pendaftaran yang dilakukan.
Kami ucapkan selamat atas diterimanya kakak menjadi salah satu volunter dalam pembuatan aplikasi Dicoding.
Selamat berkontribusi ya kak!

Regards
Dicoding Reviewer