Mendaftarkan diri sebagai Volunter
dicodingacademy/VolunterPembuatanAplikasi pull request #37
Opened 2021-07-26 09:06 UTC by aidamuhdina

Saya Aida Muhdina bersedia menjadi Volunter Pembuatan Aplikasi Dicoding

2021-07-29 07:00 UTC, dicodingreviewer requested changes

2021-07-30 08:11 UTC, aidamuhdina commented on README.md
> +* Aida Muhdina, [LinkedIn](https://www.linkedin.com/in/aida-muhdina-7917a2164/)
Terima kasih untuk reviewnya min.
Saya sudah menambahkan titik di akhir kalimat min. 
Apakah saya harus membuat pull request lagi?

2021-07-30 09:12 UTC, dicodingreviewer commented on README.md
> +* Aida Muhdina, [LinkedIn](https://www.linkedin.com/in/aida-muhdina-7917a2164/)
Mantap kak

2021-07-30 09:12 UTC, dicodingreviewer approved these changes

2021-07-30 09:12 UTC, dicodingreviewer commented on README.md
> +* Aida Muhdina, [LinkedIn](https://www.linkedin.com/in/aida-muhdina-7917a2164/).
Terima kasih atau update-nya kak.

2021-07-30 09:13 UTC, merged

2021-07-30 09:13 UTC, dicodingreviewer commented
Hai kak,

Terima kasih atas pendaftaran yang dilakukan.
Kami ucapkan selamat atas diterimanya kakak menjadi salah satu volunter dalam pembuatan aplikasi Dicoding.
Selamat berkontribusi ya kak!

Regards
Dicoding Reviewer

2021-07-30 09:23 UTC, aidamuhdina commented on README.md
> +* Aida Muhdina, [LinkedIn](https://www.linkedin.com/in/aida-muhdina-7917a2164/).
Terima kasih kembali min