Mendaftarkan Diri sebagai Volunteer
dicodingacademy/VolunterPembuatanAplikasi pull request #42
Opened 2021-07-27 02:44 UTC by toharifqi

Saya Rifqi Naufal Tohari, bersedia menjadi Volunteer Pembuatan Aplikasi Dicoding.

2021-07-27 03:48 UTC, dicodingreviewer requested changes

2021-07-27 03:48 UTC, dicodingreviewer commented on README.md
> +# Volunteer Pembuatan Aplikasi
Hai kak @toharifqi 

Maaf kak, sepertinya untuk bagian ini tidak perlu kakak ganti. Sebab, dalam [KBBI](https://kbbi.kemdikbud.go.id/entri/Volunter) kata yang tepat untuk sukarelawan adalah **Volunter**, bukan **Volunteer**. Oleh karena itu, kembalikan perubahan yang kakak lakukan. 

Terima kasih

2021-07-27 03:48 UTC, dicodingreviewer commented on README.md
> +Repository ini digunakan sebagai sayembara pencarian volunteer untuk pembuatan aplikasi Dicoding. Jika Anda tertarik untuk menjadi Volunteer, silakan lakukan PR(pull-request) pada berkas ini ya. Sila
Hai kak @toharifqi 

Untuk bagian ini, silakan lakukan seperti komentar sebelumnya ya kak.

Terima kasih

2021-07-27 03:48 UTC, dicodingreviewer commented on README.md
> +
Hai kak @toharifqi 

Untuk bagian akhir, silakan hapus enter-nya ya kak. Karena enter ini tidak diperlukan.

Terima kasih

2021-07-27 03:49 UTC, toharifqi commented on README.md
> +# Volunteer Pembuatan Aplikasi
oh baik terima kasih kak

2021-07-27 03:49 UTC, toharifqi commented on README.md
> +Repository ini digunakan sebagai sayembara pencarian volunteer untuk pembuatan aplikasi Dicoding. Jika Anda tertarik untuk menjadi Volunteer, silakan lakukan PR(pull-request) pada berkas ini ya. Sila
baik kak

2021-07-27 03:49 UTC, toharifqi commented on README.md
> +
ok siap kak

2021-07-29 07:07 UTC, dicodingreviewer approved these changes

2021-07-29 07:07 UTC, dicodingreviewer commented on README.md
> +* Rifqi Naufal Tohari, [LinkedIn](https://www.linkedin.com/in/rifqi-naufal-tohari/).
Mantap kak!

2021-07-29 07:07 UTC, merged

2021-07-29 07:07 UTC, dicodingreviewer commented
Hai kak,

Terima kasih atas pendaftaran yang dilakukan.
Kami ucapkan selamat atas diterimanya kakak menjadi salah satu volunter dalam pembuatan aplikasi Dicoding.
Selamat berkontribusi ya kak!

Regards
Dicoding Reviewer

2021-07-29 11:39 UTC, toharifqi commented
Terima kasih banyak Kak, I am very glad to learn in Dicoding